version: "2.19.1"
services:
  nextjsapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - networks
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - networks
networks:
  networks:
volumes:
  postgres: